import React, { useState } from 'react';
import { UserProfile, ReportResponse } from '../types';
import { generateStrategyReport } from '../services/geminiService';
import { Loader2 } from 'lucide-react';

const LeadForm: React.FC = () => {
  const [formData, setFormData] = useState<UserProfile>({
    fullName: '',
    email: '',
    phone: '',
    bloodType: 'O',
    lifePathNumber: '',
    disc: { d: 25, i: 25, s: 25, c: 25 }
  });

  const [isLoading, setIsLoading] = useState(false);
  const [report, setReport] = useState<ReportResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    if (name.startsWith('disc-')) {
      const key = name.split('-')[1];
      setFormData(prev => ({
        ...prev,
        disc: { ...prev.disc, [key]: Number(value) }
      }));
    } else {
      setFormData(prev => ({ ...prev, [name]: value }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    try {
      // In a real app, this would send data to a backend.
      // Here we generate the report directly via Gemini API.
      const result = await generateStrategyReport(formData);
      setReport(result);
    } catch (err) {
      setError('Có lỗi xảy ra khi tạo báo cáo. Vui lòng thử lại.');
    } finally {
      setIsLoading(false);
    }
  };

  if (report) {
    return (
      <section id="report-result" className="py-16 bg-navy-900 text-white scroll-mt-20">
        <div className="container mx-auto px-6 max-w-4xl">
            <div className="bg-white text-gray-800 p-8 md:p-12 rounded-lg shadow-2xl">
                <div className="flex justify-between items-start border-b border-gray-200 pb-6 mb-6">
                    <div>
                        <h3 className="text-2xl font-bold text-navy-900 uppercase">Báo Cáo Chiến Lược Sơ Bộ</h3>
                        <p className="text-gray-500">Dành cho: {formData.fullName}</p>
                    </div>
                    <div className="text-right hidden md:block">
                        <div className="text-sm text-gray-400">Generated by AI</div>
                        <div className="font-bold text-blue-600">STRATECIA</div>
                    </div>
                </div>

                <div className="space-y-6">
                    <div>
                        <h4 className="font-bold text-navy-900 mb-2 flex items-center">
                            <span className="w-2 h-8 bg-blue-600 mr-2 rounded-full"></span>
                            TỔNG QUAN
                        </h4>
                        <p className="text-gray-700 leading-relaxed bg-gray-50 p-4 rounded">{report.summary}</p>
                    </div>

                    <div className="grid md:grid-cols-2 gap-8">
                        <div>
                            <h4 className="font-bold text-green-700 mb-2">ĐIỂM MẠNH</h4>
                            <ul className="list-disc pl-5 space-y-1 text-gray-700">
                                {report.strengths.map((s, i) => <li key={i}>{s}</li>)}
                            </ul>
                        </div>
                        <div>
                            <h4 className="font-bold text-red-600 mb-2">ĐIỂM CẦN CẢI THIỆN</h4>
                            <ul className="list-disc pl-5 space-y-1 text-gray-700">
                                {report.weaknesses.map((w, i) => <li key={i}>{w}</li>)}
                            </ul>
                        </div>
                    </div>

                    <div>
                        <h4 className="font-bold text-navy-900 mb-2 mt-4">LỜI KHUYÊN SỰ NGHIỆP</h4>
                        <p className="text-gray-700 italic border-l-4 border-blue-400 pl-4 py-1">{report.careerAdvice}</p>
                    </div>
                    
                    <div>
                         <h4 className="font-bold text-navy-900 mb-2">CHIẾN LƯỢC ĐẦU TƯ</h4>
                        <p className="text-gray-700 italic border-l-4 border-yellow-400 pl-4 py-1">{report.investmentStrategy}</p>
                    </div>
                </div>

                <div className="mt-10 pt-6 border-t border-gray-200 text-center">
                    <p className="mb-4 font-semibold text-navy-900">Đây là bản tóm tắt. Để nhận báo cáo chi tiết 50 trang, vui lòng kiểm tra email.</p>
                    <button onClick={() => setReport(null)} className="bg-navy-900 text-white px-8 py-3 rounded hover:bg-navy-800 transition-colors">
                        Tạo báo cáo mới
                    </button>
                </div>
            </div>
        </div>
      </section>
    );
  }

  return (
    <section id="lead-form" className="py-20 bg-navy-900 text-white">
      <div className="container mx-auto px-6 flex flex-col items-center">
        
        <div className="text-center mb-10 max-w-2xl">
          <h2 className="text-3xl font-bold uppercase mb-4 text-white">Nhận báo cáo chiến lược cá nhân ngay</h2>
          <p className="text-blue-200">
            Điền thông tin bên dưới để AI phân tích và gửi bản demo báo cáo chiến lược phù hợp nhất với bạn.
          </p>
        </div>

        <form onSubmit={handleSubmit} className="w-full max-w-2xl bg-navy-800/50 p-8 rounded-xl border border-blue-500/30 shadow-2xl backdrop-blur-sm">
          <div className="space-y-4">
            
            {/* Basic Info */}
            <div>
              <input 
                type="text" 
                name="fullName"
                required
                placeholder="Họ và Tên" 
                className="w-full bg-transparent border border-blue-400/50 rounded p-3 text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300 focus:bg-navy-900/50 transition-all"
                onChange={handleChange}
                value={formData.fullName}
              />
            </div>
            
            <div>
              <input 
                type="email" 
                name="email"
                required
                placeholder="Email nhận báo cáo" 
                className="w-full bg-transparent border border-blue-400/50 rounded p-3 text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300 focus:bg-navy-900/50 transition-all"
                onChange={handleChange}
                value={formData.email}
              />
            </div>

            <div>
              <input 
                type="tel" 
                name="phone"
                required
                placeholder="Số điện thoại" 
                className="w-full bg-transparent border border-blue-400/50 rounded p-3 text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300 focus:bg-navy-900/50 transition-all"
                onChange={handleChange}
                value={formData.phone}
              />
            </div>

            {/* Specific Metrics */}
            <div className="grid grid-cols-2 gap-4">
                <select 
                    name="bloodType"
                    className="w-full bg-navy-900 border border-blue-400/50 rounded p-3 text-white focus:outline-none focus:border-blue-300"
                    onChange={handleChange}
                    value={formData.bloodType}
                >
                    <option value="A">Nhóm Máu A</option>
                    <option value="B">Nhóm Máu B</option>
                    <option value="AB">Nhóm Máu AB</option>
                    <option value="O">Nhóm Máu O</option>
                </select>

                <input 
                    type="number"
                    name="lifePathNumber"
                    placeholder="Chỉ số Đường Đời (1-9)" 
                    className="w-full bg-transparent border border-blue-400/50 rounded p-3 text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300 transition-all"
                    onChange={handleChange}
                    value={formData.lifePathNumber}
                />
            </div>

            {/* DISC Inputs */}
            <div className="pt-2">
                <label className="text-sm text-blue-200 mb-2 block">Chỉ số DISC (%) - Tổng phải bằng 100 (Ước lượng)</label>
                <div className="grid grid-cols-4 gap-2">
                    <div className="relative">
                         <input 
                            type="number"
                            name="disc-d"
                            placeholder="D"
                            min="0" max="100"
                            className="w-full bg-transparent border border-blue-400/50 rounded p-2 text-center text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300"
                            onChange={handleChange}
                            value={formData.disc.d}
                        />
                        <span className="absolute top-[-20px] left-1/2 -translate-x-1/2 text-xs text-blue-300 font-bold">D</span>
                    </div>
                    <div className="relative">
                        <input 
                            type="number"
                            name="disc-i"
                            placeholder="I"
                            min="0" max="100"
                            className="w-full bg-transparent border border-blue-400/50 rounded p-2 text-center text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300"
                            onChange={handleChange}
                            value={formData.disc.i}
                        />
                        <span className="absolute top-[-20px] left-1/2 -translate-x-1/2 text-xs text-blue-300 font-bold">I</span>
                    </div>
                    <div className="relative">
                        <input 
                            type="number"
                            name="disc-s"
                            placeholder="S"
                            min="0" max="100"
                            className="w-full bg-transparent border border-blue-400/50 rounded p-2 text-center text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300"
                            onChange={handleChange}
                            value={formData.disc.s}
                        />
                         <span className="absolute top-[-20px] left-1/2 -translate-x-1/2 text-xs text-blue-300 font-bold">S</span>
                    </div>
                    <div className="relative">
                        <input 
                            type="number"
                            name="disc-c"
                            placeholder="C"
                            min="0" max="100"
                            className="w-full bg-transparent border border-blue-400/50 rounded p-2 text-center text-white placeholder-blue-200/50 focus:outline-none focus:border-blue-300"
                            onChange={handleChange}
                            value={formData.disc.c}
                        />
                        <span className="absolute top-[-20px] left-1/2 -translate-x-1/2 text-xs text-blue-300 font-bold">C</span>
                    </div>
                </div>
            </div>

            {error && (
                <div className="text-red-400 text-sm bg-red-900/20 p-2 rounded text-center">{error}</div>
            )}

            <button 
                type="submit"
                disabled={isLoading}
                className="w-full bg-white text-navy-900 font-bold text-lg py-4 rounded mt-6 hover:bg-blue-50 transition-colors shadow-lg uppercase tracking-wider disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
                {isLoading ? (
                    <>
                        <Loader2 className="animate-spin" />
                        Đang phân tích...
                    </>
                ) : (
                    "Gửi Báo Cáo Vào Email"
                )}
            </button>
            
            <p className="text-xs text-blue-300/60 text-center mt-4">
                *Bằng việc nhấn gửi, bạn đồng ý nhận thông tin tư vấn từ Stratecia.
            </p>
          </div>
        </form>
      </div>
    </section>
  );
};

export default LeadForm;